/**
 * Vereth SGX Proof Verifier
 * 
 * Main entry point for verifying SGX proofs generated by Vereth
 */

export * from './types';
export * from './verifier';
export * from './proof';
export * from './abi';
export * from './utils';
export * from './rpc';
export * from './block';
export * from './verifier-chain';
export * from './quote';

// Re-export main functions for convenience
export { verifySingleProof, verifyBatchProof } from './verifier';
export { verifySingleProofFromChain, verifyBatchProofFromChain } from './verifier-chain';
export { parseProof, recoverSigner } from './proof';
export { calculateInstanceHash } from './abi';
export { fetchBlock, fetchBlocks, getChainConfig } from './rpc';

